
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjpmgsdggnrwccclqmdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcG1nc2RnZ25yd2NjY2xxbWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDk4MTYsImV4cCI6MjA2MzU4NTgxNn0.r9pX-EWPsFMX8oCE7Tx6aB-IgXUtiyobNErnC0lpnE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
